const actions = {
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  FLUSH_CART: "FLUSH_CART",
  SET_SEARCH: "SET_SEARCH",
  SET_MANUFACTURER: "SET_MANUFACTURER",
  SET_EMAIL: "SET_EMAIL",
  SET_MESSAGE: "SET_MESSAGE",
  FLUSH_CONTACT_FORM: "FLUSH_CONTACT_FORM",
  SET_ERROR_CONTACT_FORM: "SET_ERROR_CONTACT_FORM",
};

export default actions;
